appName: transaction-worker

deployment:
  enabled: true
  replicaCount: 1
  image:
    repository: stagemicroservices.azurecr.io/devops_showcase_transaction_service
    tag: "latest"
    pullPolicy: IfNotPresent
  secretName: default-certificate-secrets #this secret is not used anymore soooo #TODO delete from all files 

  command: ["celery"]
  args: ["-A", "celery_app", "worker", "-n", "transaction_worker", "--loglevel=info", "-Q", "transaction_queue"]

  containerPorts: []

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  readinessProbe: {}
  livenessProbe: {}

  runAsUser: 1000
  fsGroup: 1000

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%

service:
  enabled: false


secrets:
  _isFrontend: false
  _isFlaskApp: true
  _isCartService: false

  flask:
    FLASK_APP: "run.py"
    FLASK_ENV: "developmenti"
    SECRET_KEY: "f6fa81b24da5ea0b8f46149bb3392e16cbe3702935cf7e1c"
    MONGODB_DB: "devopsshowcase"
    MONGODB_HOST: "mongodb"
    MONGODB_PORT: "27017"
    MONGODB_USERNAME: "genocemuser"
    MONGODB_PASSWORD: "123passwordSecret123"
    MONGODB_AUTH_SOURCE: "devopsshowcase"
    SESSION_COOKIE_SECURE: true
    SESSION_COOKIE_HTTPONLY: true
    SESSION_COOKIE_SAMESITE: Lax
    CELERY_BROKER_HOST: redis
    CELERY_BROKER_PORT: 6379
