apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appName }}-secrets
  labels:
    app: {{ .Values.appName }}
type: Opaque
stringData:
  {{- if .Values.secrets._isFlaskApp }}
  {{- range $key, $value := .Values.secrets.flask }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}

  {{- if .Values.secrets._isFrontend }}
  {{- range $key, $value := .Values.secrets.frontend }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}

  {{- if .Values.secrets._isCartService }}
  {{- range $key, $value := .Values.secrets.cart }}
  {{ $key }}: "{{ $value }}"
  {{- end }}
  {{- end }}